# Generated by Django 4.2.11 on 2026-05-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('original_headers', models.JSONField(blank=True, default=list)),
                ('mapped_headers', models.JSONField(blank=True, default=dict)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Regex validation rules per column')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HeaderMappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('original_headers', models.JSONField(default=list)),
                ('mapped_headers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('data_type', 'Data Type Validation'), ('required', 'Required Field'), ('business', 'Business Rule')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=255)),
                ('rule_config', models.JSONField(default=dict, help_text='Configuration for the validation rule')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_type', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('valid_rows_count', models.IntegerField(default=0)),
                ('invalid_rows_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_reports', to='excel_processor.excelupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
