# Generated by Django 4.2.11 on 2026-05-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='validation_options',
            field=models.JSONField(blank=True, default=dict, help_text='Validation options like check_duplicates, check_empty_values'),
        ),
    ]
