# Generated by Django 4.2.11 on 2026-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0002_excelupload_validation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationreport',
            name='output_file',
            field=models.FileField(blank=True, help_text='Pre-generated validated Excel file for fast download', null=True, upload_to='validated/%Y/%m/%d/'),
        ),
    ]
