# Generated by Django 4.2.11 on 2026-05-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0003_validationreport_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationreport',
            name='Valid_records_file',
            field=models.FileField(blank=True, help_text='Excel file with only valid/good records', null=True, upload_to='validated/good/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='rejected_records_file',
            field=models.FileField(blank=True, help_text='Excel file with only rejected records and errors', null=True, upload_to='validated/rejected/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processed'), (2, 'All Rejected')], default=0, help_text='0=Pending, 1=Processed, 2=All Rejected'),
        ),
    ]
