# Generated by Django 4.2.11 on 2026-05-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0004_validationreport_good_records_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='Celery task ID', max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('current_step', models.CharField(blank=True, help_text='Current processing step', max_length=100)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('output_file_path', models.CharField(blank=True, help_text='Path to all records file', max_length=500, null=True)),
                ('good_records_file_path', models.CharField(blank=True, help_text='Path to good records file', max_length=500, null=True)),
                ('rejected_records_file_path', models.CharField(blank=True, help_text='Path to rejected records file', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_logs', models.JSONField(blank=True, default=list, help_text='Array of log messages with timestamps')),
                ('excel_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_jobs', to='excel_processor.excelupload')),
                ('validation_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_jobs', to='excel_processor.validationreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_id'], name='excel_proce_job_id_23a7c9_idx'), models.Index(fields=['status'], name='excel_proce_status_6db71f_idx'), models.Index(fields=['-created_at'], name='excel_proce_created_f6986c_idx')],
            },
        ),
    ]
